; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115200
extra_scripts = pre:sync_version.py
lib_deps = 
	https://github.com/JimorMarlow/etl@^0.9.8
	gyverlibs/GyverDS18@^1.2.0
	gyverlibs/GTimer@^1.1.1
	gyverlibs/FileData@^1.0.3
	marcoschwartz/LiquidCrystal_I2C@^1.1.4

[env:nodemcuv3]
platform = espressif8266
board = nodemcuv2
board_build.filesystem = littlefs
build_flags = 
	-D BOARD_NODEMCU
	${env.build_flags}
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_MD5

